package br.com.srportto.exemplos;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;

public final class ProcessadorIdempotente {
    /** Mesma chave de idempotência com payload diferente: conflito, nunca sobrescrita silenciosa. */
    public static final class ConflitoDeChave extends IllegalArgumentException {
        ConflitoDeChave(String mensagem) { super(mensagem); }
    }

    private final DataSource banco;
    public ProcessadorIdempotente(DataSource banco) { this.banco = Objects.requireNonNull(banco); }

    public void preparar() throws SQLException {
        try (var conexao = banco.getConnection(); var comando = conexao.createStatement()) {
            comando.execute("CREATE TABLE IF NOT EXISTS pedidos (id VARCHAR(36) PRIMARY KEY, centavos BIGINT NOT NULL)");
            comando.execute("CREATE TABLE IF NOT EXISTS idempotencia (tenant VARCHAR(80), chave VARCHAR(80), centavos BIGINT NOT NULL, resultado VARCHAR(36) NOT NULL, PRIMARY KEY(tenant, chave))");
            // A sequência define a ordem de publicação; UUID aleatório não preserva ordem de criação.
            comando.execute("CREATE TABLE IF NOT EXISTS outbox (seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "id VARCHAR(36) NOT NULL UNIQUE, publicado BOOLEAN NOT NULL)");
        }
    }

    public String processar(String tenant, String chave, long centavos) throws SQLException {
        if (tenant == null || tenant.isBlank() || tenant.length() > 80 ||
                chave == null || chave.isBlank() || chave.length() > 80 || centavos <= 0)
            throw new IllegalArgumentException("Pedido inválido");
        try (var conexao = banco.getConnection()) {
            conexao.setAutoCommit(false);
            try {
                String id = UUID.randomUUID().toString();
                try (var reserva = conexao.prepareStatement("INSERT INTO idempotencia(tenant,chave,centavos,resultado) VALUES(?,?,?,?)")) {
                    reserva.setString(1, tenant); reserva.setString(2, chave);
                    reserva.setLong(3, centavos); reserva.setString(4, id); reserva.executeUpdate();
                }
                try (var pedido = conexao.prepareStatement("INSERT INTO pedidos(id,centavos) VALUES(?,?)")) {
                    pedido.setString(1, id); pedido.setLong(2, centavos); pedido.executeUpdate();
                }
                try (var evento = conexao.prepareStatement("INSERT INTO outbox(id,publicado) VALUES(?,false)")) {
                    evento.setString(1, id); evento.executeUpdate();
                }
                conexao.commit();
                return id;
            } catch (SQLException erro) {
                conexao.rollback();
                if (!"23505".equals(erro.getSQLState())) throw erro;
                // A restrição única arbitra a corrida entre conexões/instâncias.
                return resultadoAnterior(tenant, chave, centavos);
            } catch (RuntimeException erro) {
                conexao.rollback(); throw erro;
            }
        }
    }

    private String resultadoAnterior(String tenant, String chave, long centavos) throws SQLException {
        try (var conexao = banco.getConnection();
             var consulta = conexao.prepareStatement("SELECT centavos,resultado FROM idempotencia WHERE tenant=? AND chave=?")) {
            consulta.setString(1, tenant); consulta.setString(2, chave);
            try (var resultado = consulta.executeQuery()) {
                if (!resultado.next()) throw new SQLException("Resultado idempotente ausente");
                if (resultado.getLong(1) != centavos) throw new ConflitoDeChave("Chave reutilizada com payload diferente");
                return resultado.getString(2);
            }
        }
    }

    public long quantidadePedidos() throws SQLException {
        try (var conexao = banco.getConnection(); var consulta = conexao.createStatement();
             var resultado = consulta.executeQuery("SELECT COUNT(*) FROM pedidos")) {
            resultado.next(); return resultado.getLong(1);
        }
    }
}

